version: '3.7'

services: 
  instagram_db:
    container_name: instagram_db 
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=instagram
      - POSTGRES_PASSWORD=root
    image: postgres:15.3-alpine